### ISSUE TITLE
Feat: Transform Links to `target="_blank"`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/link#14]
One of the requirements in https://github.com/dwyl/mvp/issues/141 is to open `URLs` in a New Tab. 

Did a quick `dbg` in the `MVP` and this is the output of `Earmark.as_html!()`:
```
markdown #=> "Test links in MVP: https://amemo.fly.dev/"
|> Link.find_replace_compact() #=> "Test links in MVP: [amemo.fly.dev](https://amemo.fly.dev/)"
|> Earmark.as_html!() #=> "<p>\nTest links in MVP: <a href=\"https://amemo.fly.dev/\">amemo.fly.dev</a></p>\n"
```

So it should be straightforward to replace `<a href=` with `<a target=\"_blank\" href=` 💭 

# Todo

+ [x] Write a test for each case: 🧑‍💻 
  + [x] No `URL` in the `text`
  + [x] Only _one_ `URL` in the `text`
  + [x] _Multiple_ `URLs` in the `text`
+ [x] Implement a `add_target_blank/1` function 
+ [x] Publish a new version of the package to `hex.pm` 📦

**Comment by nelsonic** [comment]
```elixir
  @doc """
  `add_target_blank/1` Adds the target="_blank" attribute to links
  so that links open in a new Tab/Window.

  ## Examples

      iex> Link.add_target_blank(~s(My <a href="https://link.com">Link</a>))
      ~s(My <a target="_blank" href="https://link.com">Link</a>)
  """
  def add_target_blank(text) do
    String.replace(text, "<a href=", "<a target=\"_blank\" href=")
  end
```

**Comment by nelsonic** [comment]
```elixir

  test "Link.add_target_blank/1 no link" do
    text = "Random text without any URLs"
    assert Link.add_target_blank(text) == text
  end

  test "Link.add_target_blank/1 replaces <a href= with <a target=\"_blank\" href=" do
    text = "<p>\nTarget _blank links: <a href=\"https://amemo.fly.dev/\">amemo.fly.dev</a></p>\n"
    assert Link.add_target_blank(text) ==
      "<p>\nTarget _blank links: <a target=\"_blank\" href=\"https://amemo.fly.dev/\">amemo.fly.dev</a></p>\n"
  end

  test "Link.add_target_blank/1 replaces multiple URLs" do
    text = "<p>My awesome <a href=\"https://link.com\">Link</a> <a href=\"https://foo.bar\">Foo</a></p>"
    assert Link.add_target_blank(text) ==
      "<p>My awesome <a target=\"_blank\" href=\"https://link.com\">Link</a> <a target=\"_blank\" href=\"https://foo.bar\">Foo</a></p>"
  end
```

**Comment by nelsonic** [comment]
https://hexdocs.pm/link/1.0.11/Link.html#add_target_blank/1
