### ISSUE TITLE
`Link.find/1` should `find` all URLs in a `String` and return a `List`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/link#4]
At present we are able to render markdown without any URL-shorting: 
That’s fine for compact urls like https://mvp.fly.dev/ 
But the moment you have an issue comment like: 
https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420
It takes up half the screen and on mobile it wraps and looks fugly. 

So … I want to use [`Link.compact/1`](https://github.com/dwyl/link#usage-examples-)
to _automagically_ turn https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420
into [dwyl/mvp#141](https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420).

To achieve that we need to first `find` all the links in a block of `text` (`String`).

Given a block of text with links https://mvp.fly.dev/ in it, `find` all the links https://dwyl.com/ 
in the `String` 
then compact/shorten the links 
and re-assemble the parts back into a string 
then render the Markdown.

Just spent 30 mins trawling `Google`, `StackOverflow` and `GitHub`
and this `RegEx` _appears_ to be the most compact yet complete one: https://regexr.com/39nr7

```sh
/[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/ig
```

# Todo

+ [x] Create a `public` helper function `Link.regex/0` that simply returns the `RegEx` for use in _any_ situation. 
  Sadly, https://hexdocs.pm/elixir/1.13/URI.html the core `URI` module does not expose anything we can use ... 🙄 
  + [x] Write tests with as _many_ examples as possible so that we have some certainty it's working. 
+ [x] Create `Link.find/1` function that finds all instances of `URLs` in a block of text.
+ [x] Create `Link.find_replace_compact/1` that finds all links in a block of text and replaces them with compacted versions.

**Comment by nelsonic** [comment]
For giggles I axksed ChatGPT: https://chat.openai.com/c/aa0d0d53-ee1e-449b-ac83-04fa6a9bb6f6
<img width="1076" alt="image" src="https://github.com/dwyl/link/assets/194400/23d905b8-ab60-468e-8338-1f14ccc3f585">


```elixir
regex_pattern = ~r{^(?:(?:https?|ftp):\/\/)?(?:[a-z0-9.-]+|\[[a-fA-F0-9:]+\])(?::\d+)?(?:\/[^?\n\r]*)?(?:\?[^\n\r]*)?(?:#[^\n\r]*)?$}
```

Sadly it produces `false` positives ...

```elixir
iex> text = "text has.com links http://www.links.net in it"
iex> Regex.scan(regex_pattern , text)
["text", "has.com", "links", "http://www.links.net", "in", "it"]
````

Better luck next time [Uncle Sam](https://github.com/nelsonic/nelsonic.github.io/issues/733#issuecomment-1658877671) 🙃

**Comment by nelsonic** [comment]
```elixir
[1, 2, 3, 4] 
  |> Enum.chunk_every(1) 
  |> Enum.map(fn [i] -> {i, i * 2} end) 
  |> Map.new
```

**Comment by nelsonic** [comment]
On reflection, my implementation of [`Link.find_replace_compact/1`](https://github.com/dwyl/link/commit/3ce7a27c8771380d9492b3b05306c9679ee5e196)
Will actually mess up a Markdown file that:
a) already has links in it
b) has images ... 

So I need to re-think this. 💭

**Comment by nelsonic** [comment]
Gonna take a quick look at this now.

**Comment by nelsonic** [comment]
# Working! 🚀 

```md
My long link https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420
```

Is compacted to:
```md
My long link [dwyl/mvp#141](https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420)
```
i.e: My long link [dwyl/mvp#141](https://github.com/dwyl/mvp/issues/141#issuecomment-1657954420)

https://amemo.fly.dev/
<img width="858" alt="image" src="https://github.com/dwyl/link/assets/194400/e2eae817-1561-4b86-aba3-216679c07891">

**Comment by nelsonic** [comment]
Included in PR #5
