### ISSUE TITLE
Chore: compact `GitHub` repo `URL` e.g: `https://github.com/dwyl/link/`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/link#9]
As noted by @LuchoTurtle in https://github.com/dwyl/link/pull/5#pullrequestreview-1573520109 the repo URL `https://github.com/dwyl/link` is not compacted:

<img width="716" alt="link-repo-url-not-compacted" src="https://github.com/dwyl/link/assets/194400/39c93b57-6e49-4131-8622-dc3ea1261b37">

# Todo

+ [x] Review the _existing_ tests for repo URLs:
https://github.com/dwyl/link/blob/ae0127d20e897247dd0ceb215cbdc1bedd9af373/lib/link.ex#L41-L54
Currently no `doctest` or specific test for _just_ the repo URL ...
+ [x] Create `doctest` for just the base URL  `https://github.com/dwyl/link/` should compact to: `dwyl/link`
+ [x] Make the `doctest` pass without breaking any existing tests.
+ [x] Bump version in `mix.exs` and `README.md` to release the fix.
+ [x] Create PR & assign for review
+ [x] Publish to `hex.pm`
